### ISSUE TITLE
The Dataset

### ISSUE THREAD

**Issue by sli1990** [bayesian-object-tracking/dbot#3]
Dera Jan,

where can we find the depth based tracking dataset from your paper:
"Depth-based Object Tracking Using a Robust Gaussian Filter " ?

Thanks

**Comment by cassinaj** [comment]
Hi sli1990,

the dataset links will be published here on May 15th. This is the same date of the publication of this paper at ICRA 2016 in Stockholm.

Few notes on the dataset. The recorded format requires OpenNI 1.5 and it seems that many people are having issues with OpenNI 1.x. Nevertheless, the original dataset will be published, and we are preparing  a converted version which works with the more stable OpenNI2.0.

For more details, feel free to contact me at jan.issac@gmail.com.

**Comment by jbohg** [comment]
The dataset is published here. https://github.com/bayesian-object-tracking/object_tracking_dataset
